services:

  main:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto-main.conf:/mosquitto/config/mosquitto.conf"
  
  generate-certificates:
    build:
      dockerfile: ./certificate-generator.Dockerfile
      # Add these arguments if you are stuck behind a proxy
      # args:
      #   HTTP_PROXY: 
      #   HTTPS_PROXY: 
    environment:
      IP: "127.0.0.1"
      HOSTS: example.org,example.de,example.com
    volumes:
      - "./certificates:/certificates"
  
  secure-bridge:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes: 
      - "./mosquitto-secure.conf:/mosquitto/config/mosquitto.conf"
      - "./password.txt:/mosquitto/config/password.txt"
      - "./certificates:/certs"
    depends_on:
      generate-certificates:
        condition: service_completed_successfully