services:
  mosquitto:
    build: ./mosquitto
    #container_name: mosquitto-secure
    ports:
      - "8883:8883"
    environment:
      - MQTT_IP=127.0.0.1
    volumes:
      - ./mosquitto/config:/mosquitto/config
      #- ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/certs
    restart: unless-stopped